--MEMBER,MISSION,MEMBER_MISSION,MISSION_CATEGORY,ANALYSIS,ROUTINE,BOOKMARK,상태조사 
--'상태조사' 테이블 만들어야 함. 

--시퀀스 삭제 
DROP SEQUENCE SEQ_MEMBER; 
DROP SEQUENCE SEQ_MISSION; 
DROP SEQUENCE SEQ_MEMBER_MISSION;
DROP SEQUENCE SEQ_MISSION_CATEGORY;
DROP SEQUENCE SEQ_ANALYSIS; 
DROP SEQUENCE SEQ_ROUTINE; 
DROP SEQUENCE SEQ_BOOKMARK; 

--테이블 삭제
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MISSION CASCADE CONSTRAINTS;
DROP TABLE MEMBER_MISSION CASCADE CONSTRAINTS;
DROP TABLE MISSION_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE ANALYSIS CASCADE CONSTRAINTS;
DROP TABLE ROUTINE CASCADE CONSTRAINTS;
DROP TABLE BOOKMARK CASCADE CONSTRAINTS;

--시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE; 
CREATE SEQUENCE SEQ_MISSION NOCACHE NOCYCLE; 
CREATE SEQUENCE SEQ_MEMBER_MISSION NOCACHE NOCYCLE; 
CREATE SEQUENCE SEQ_MISSION_CATEGORY NOCACHE NOCYCLE; 
CREATE SEQUENCE SEQ_ANALYSIS NOCACHE NOCYCLE; 
CREATE SEQUENCE SEQ_ROUTINE NOCACHE NOCYCLE; 
CREATE SEQUENCE SEQ_BOOKMARK NOCACHE NOCYCLE; 

--테이블 생성
CREATE TABLE MEMBER (
	NO	            NUMBER		    PRIMARY KEY,
    NAME	        VARCHAR2(10)	NOT NULL,
    EMAIL           VARCHAR2(30)    NOT NULL,
	ID	            VARCHAR2(30)	NOT NULL
);

CREATE TABLE MISSION (
	NO	            NUMBER		    PRIMARY KEY,
	CATEGORY_NO	    NUMBER      	NOT NULL,
	NAME	        VARCHAR2(50)	NOT NULL,
	REVIEW	        VARCHAR2(30)	NOT NULL,
	PHOTO	        VARCHAR2(400)	NULL,
	STAMP	        VARCHAR2(400)	NULL
);

CREATE TABLE MEMBER_MISSION (
	MEMBER_MISSION_NO	    NUMBER	    PRIMARY KEY,
	MEMBER_NO	            NUMBER	    NOT NULL,
	MISSION_NO	            NUMBER	    NULL,
	ROUTINE_NO	            NUMBER	    NULL,
	MISSION_DATE	        TIMESTAMP	NOT NULL	
);

CREATE TABLE MISSION_CATEGORY (
	CATEGORY_NO	    NUMBER	        PRIMARY KEY,
	NAME	        VARCHAR2(10)	NOT NULL
);

CREATE TABLE ANALYSIS (
	ANAL_NO	            NUMBER		PRIMARY KEY,
	MEMBER_NO	        NUMBER		NOT NULL,
	MEMBER_MISSION_NO   NUMBER      NOT NULL
);

CREATE TABLE ROUTINE (
	ROUTINE_NO	NUMBER		    PRIMARY KEY,
	MEMBER_NO	NUMBER		    NOT NULL,
	NAME	    VARCHAR2(15)	NOT NULL,
	REPEAT_DAY	VARCHAR2(100)	NOT NULL,
	IS_ALARM	CHAR(1)		    DEFAULT 'N' CHECK(IS_ALARM IN ('Y', 'N')),
	ALARM_TIME  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATE_DAY	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP,
--    ROUTINE NAME에 대한 제약조건 추가 
    CONSTRAINT NAME_LENGTH CHECK (LENGTH(NAME)<= 15)
);

CREATE TABLE BOOKMARK (
	BOOKMARK_NO	    NUMBER		PRIMARY KEY,
	MEMBER_NO	    NUMBER		NOT NULL,
	CREATE_DATE	    TIMESTAMP	NULL,
--  프론트가 POST_NO를 어떻게 처리하냐에 따라 POST_NO에 해당하는 제약조건CHECK를 추가하기    
	POST_NO	        NUMBER		
);

--외래키
ALTER TABLE MISSION
ADD CONSTRAINT FK_MISSION_CATEGORY_NO
FOREIGN KEY (CATEGORY_NO)
REFERENCES MISSION_CATEGORY(CATEGORY_NO);

ALTER TABLE MEMBER_MISSION 
ADD CONSTRAINT FK_MISSION_MEMBER_NO
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (NO);

ALTER TABLE MEMBER_MISSION
ADD CONSTRAINT FK_MISSION_MISSION_NO
FOREIGN KEY (MISSION_NO)
REFERENCES MISSION (NO);

ALTER TABLE MEMBER_MISSION
ADD CONSTRAINT FK_MISSION_ROUTINE_NO
FOREIGN KEY (ROUTINE_NO)
REFERENCES ROUTINE (ROUTINE_NO);

ALTER TABLE ANALYSIS 
ADD CONSTRAINT FK_ANALYSIS_MEMBER
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER(NO);

ALTER TABLE ANALYSIS
ADD CONSTRAINT FK_ANALYSIS_MEMBER_MISSION
FOREIGN KEY (MEMBER_MISSION_NO)
REFERENCES MEMBER_MISSION(MEMBER_MISSION_NO);

ALTER TABLE ROUTINE 
ADD CONSTRAINT FK_ROUTINE_MEMBER_NO
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER(NO);

ALTER TABLE BOOKMARK
ADD CONSTRAINT FK_BOOKMARK_MEMBER_NO
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER(NO);